package com.ehootu.census.dao;

import com.ehootu.census.model.Destinations;
import com.ehootu.census.model.DestinationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DestinationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    long countByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int deleteByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int deleteByPrimaryKey(Integer destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int insert(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int insertSelective(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    List<Destinations> selectByExample(DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    Destinations selectByPrimaryKey(Integer destinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Destinations record, @Param("example") DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int updateByExample(@Param("record") Destinations record, @Param("example") DestinationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int updateByPrimaryKeySelective(Destinations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinations
     *
     * @mbg.generated Wed Jul 25 17:12:30 CST 2018
     */
    int updateByPrimaryKey(Destinations record);
}